import { Link, useParams } from "react-router";
import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, CheckCircle2, Clock3, Database, Plus, RefreshCw, XCircle } from "lucide-react";
import { Badge } from "../components/ui/badge";
import { Button } from "../components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "../components/ui/card";

type NativeScript = { type: string; keyHash?: string; scripts?: NativeScript[]; required?: number; slot?: number; [key: string]: unknown };
type Signer = { id: string; label: string; keyHash: string; source?: "payment" | "stake" | "manual" };
type Wallet = { id: string; name: string; network: string; threshold: number; signers: Signer[]; paymentScript: NativeScript; stakeScript?: NativeScript | null; imported: boolean; createdAt: string };
type SignatureRecord = { signerKeyHash: string; signerName: string; walletName: string; witnessCbor: string; signedAt: string };
type AssetLine = { id: string; unit: string; label: string; quantity: string };
type AssetOption = { unit: string; label: string; quantity: string; outputCount?: number };
type TxStatus = "pending" | "succeeded" | "failed";
type TxDraft = { id: string; walletId?: string; title: string; walletName: string; network: string; recipient: string; lovelace: string; note: string; unsignedTxCbor: string; requiredSignatures: number; signerKeyHashes: string[]; signatures: SignatureRecord[]; assets?: AssetLine[]; status?: TxStatus; createdAt: string; updatedAt?: string; txHash?: string; failureReason?: string };
const WALLET_KEY = "cardano-multisig.wallets.v2";
const TX_KEY = "cardano-multisig.transactions.v1";

export function meta() { return [{ title: "Wallet · Cardano Multisig" }]; }
function readArray<T>(key: string): T[] { if (typeof window === "undefined") return []; try { const parsed = JSON.parse(window.localStorage.getItem(key) || "[]"); return Array.isArray(parsed) ? parsed as T[] : []; } catch { return []; } }
function writeArray<T>(key: string, value: T[]) { window.localStorage.setItem(key, JSON.stringify(value, null, 2)); }
function summarizeScript(script?: NativeScript | null) { if (!script) return "not provided"; const leaves = countLeaves(script); if (script.type === "sig") return "1-of-1"; if (script.type === "any") return `1-of-${leaves}`; if (script.type === "all") return `${leaves}-of-${leaves}`; if (script.type === "atLeast") return `${script.required ?? 0}-of-${leaves}`; return script.type; }
function countLeaves(script: NativeScript): number { if (script.type === "sig") return 1; return Array.isArray(script.scripts) ? script.scripts.reduce((sum, child) => sum + countLeaves(child), 0) : 0; }
function signedCount(tx: TxDraft) { const signed = new Set((tx.signatures || []).map((sig) => sig.signerKeyHash.toLowerCase())); return (tx.signerKeyHashes || []).filter((hash) => signed.has(hash.toLowerCase())).length; }
function txStatus(tx: TxDraft): TxStatus { return tx.status || "pending"; }
function statusBadge(status: TxStatus) { if (status === "succeeded") return "default" as const; if (status === "failed") return "destructive" as const; return "outline" as const; }
function statusIcon(status: TxStatus) { if (status === "succeeded") return <CheckCircle2 className="size-4 text-emerald-300" />; if (status === "failed") return <XCircle className="size-4 text-red-300" />; return <Clock3 className="size-4 text-amber-300" />; }
function displayQuantity(quantity: string, unit: string) { if (unit !== "lovelace") return quantity || "0"; const value = Number(quantity || "0") / 1_000_000; return Number.isFinite(value) ? `${value.toLocaleString(undefined, { maximumFractionDigits: 6 })} ADA` : `${quantity} lovelace`; }
function scriptToCsl(CSL: any, script: NativeScript): any {
  if (script.type === "sig" && script.keyHash) return CSL.NativeScript.new_script_pubkey(CSL.ScriptPubkey.new(CSL.Ed25519KeyHash.from_hex(script.keyHash)));
  const children = CSL.NativeScripts.new();
  for (const child of script.scripts || []) children.add(scriptToCsl(CSL, child));
  if (script.type === "all") return CSL.NativeScript.new_script_all(CSL.ScriptAll.new(children));
  if (script.type === "any") return CSL.NativeScript.new_script_any(CSL.ScriptAny.new(children));
  if (script.type === "atLeast") return CSL.NativeScript.new_script_n_of_k(CSL.ScriptNOfK.new(Number(script.required || 1), children));
  throw new Error(`Unsupported native script type: ${script.type}`);
}
async function paymentScriptPattern(wallet: Wallet) { if (!wallet.paymentScript) return null; try { const CSL = await import("@emurgo/cardano-serialization-lib-browser"); const paymentHash = scriptToCsl(CSL, wallet.paymentScript).hash().to_hex(); const isMainnet = wallet.network === "mainnet"; if (wallet.stakeScript) { const stakeHash = scriptToCsl(CSL, wallet.stakeScript).hash().to_hex(); return `${isMainnet ? "31" : "30"}${paymentHash}${stakeHash}`; } return `${isMainnet ? "71" : "70"}${paymentHash}`; } catch { return null; } }
async function fetchWalletAssets(wallet: Wallet): Promise<AssetOption[]> { const pattern = await paymentScriptPattern(wallet); if (!pattern) throw new Error("Could not derive wallet script hash."); const res = await fetch(`/api/cardano/assets?pattern=${encodeURIComponent(pattern)}`); const body = await res.json(); if (!res.ok) throw new Error(body.error || "Could not load multisig assets."); return body.assets || []; }

export default function WalletDetail() {
  const { walletId } = useParams();
  const [wallets, setWallets] = useState<Wallet[]>([]);
  const [txs, setTxs] = useState<TxDraft[]>([]);
  const [walletAssets, setWalletAssets] = useState<AssetOption[]>([]);
  const [assetStatus, setAssetStatus] = useState("Loading multisig assets…");
  useEffect(() => { setWallets(readArray<Wallet>(WALLET_KEY)); setTxs(readArray<TxDraft>(TX_KEY)); }, []);
  const wallet = wallets.find((item) => item.id === walletId);
  const walletTxs = useMemo(() => txs.filter((tx) => tx.walletId === walletId || (!tx.walletId && wallet && tx.walletName === wallet.name)).sort((a,b) => (b.createdAt || "").localeCompare(a.createdAt || "")), [txs, wallet, walletId]);
  function updateStatus(id: string, status: TxStatus) { const next = txs.map((tx) => tx.id === id ? { ...tx, status, updatedAt: new Date().toISOString() } : tx); setTxs(next); writeArray(TX_KEY, next); }
  async function refreshAssets(target = wallet) { if (!target) return; setAssetStatus("Loading multisig assets from Kupo…"); try { const assets = await fetchWalletAssets(target); setWalletAssets(assets); setAssetStatus(assets.length ? `Loaded ${assets.length} multisig asset${assets.length === 1 ? "" : "s"}.` : "No spendable multisig assets found yet."); } catch (error) { setWalletAssets([]); setAssetStatus(error instanceof Error ? error.message : "Could not load multisig assets."); } }
  useEffect(() => { if (wallet) void refreshAssets(wallet); }, [wallet?.id]);

  if (!wallet) return <main className="mx-auto max-w-5xl px-4 py-8 text-slate-100"><Link className="text-sm text-sky-300" to="/">← Back</Link><Card className="glass-panel mt-6"><CardContent className="p-8 text-slate-300">Wallet not found in this browser. Import or create it first.</CardContent></Card></main>;
  const pending = walletTxs.filter((tx) => txStatus(tx) === "pending").length;
  const succeeded = walletTxs.filter((tx) => txStatus(tx) === "succeeded").length;
  const failed = walletTxs.filter((tx) => txStatus(tx) === "failed").length;

  return <main className="mx-auto flex w-full max-w-7xl flex-col gap-6 px-4 py-8 text-slate-100 sm:px-6 lg:px-8">
    <div className="flex flex-wrap items-center justify-between gap-4"><div><Link to="/" className="inline-flex items-center gap-2 text-sm text-sky-300"><ArrowLeft className="size-4" /> Back to wallets</Link><h1 className="mt-3 text-4xl font-semibold tracking-[-0.06em] text-slate-50">{wallet.name}</h1><p className="mt-2 text-slate-400">{wallet.network} · {wallet.signers.length} signers · payment {summarizeScript(wallet.paymentScript)} · stake {summarizeScript(wallet.stakeScript)}</p></div><a href={`/wallets/${encodeURIComponent(wallet.id)}/transactions/new`} className="inline-flex h-10 items-center justify-center gap-2 rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow-xs transition hover:bg-primary/90"><Plus className="size-4" /> Create transaction</a></div>
    <section className="grid gap-4 md:grid-cols-4"><Card className="glass-panel"><CardContent className="p-4"><div className="text-2xl font-semibold text-sky-200">{walletTxs.length}</div><div className="text-xs text-slate-400">transactions</div></CardContent></Card><Card className="glass-panel"><CardContent className="p-4"><div className="text-2xl font-semibold text-amber-300">{pending}</div><div className="text-xs text-slate-400">pending</div></CardContent></Card><Card className="glass-panel"><CardContent className="p-4"><div className="text-2xl font-semibold text-emerald-300">{succeeded}</div><div className="text-xs text-slate-400">succeeded</div></CardContent></Card><Card className="glass-panel"><CardContent className="p-4"><div className="text-2xl font-semibold text-red-300">{failed}</div><div className="text-xs text-slate-400">failed</div></CardContent></Card></section>
    <Card className="glass-panel"><CardHeader><div className="flex flex-wrap items-center justify-between gap-3"><div><CardTitle>Multisig assets</CardTitle><CardDescription>Fetched from the server-managed Kupo indexer for this script wallet.</CardDescription></div><Button variant="secondary" size="sm" onClick={() => refreshAssets()}><RefreshCw className="size-4" /> Refresh</Button></div></CardHeader><CardContent>{walletAssets.length === 0 ? <div className="rounded-lg border border-border bg-slate-950/60 p-4 text-sm text-slate-400"><Database className="mr-2 inline size-4 text-sky-300" /> {assetStatus}</div> : <div className="grid gap-3 md:grid-cols-3">{walletAssets.map((asset) => <div className="rounded-lg border border-border bg-slate-950/60 p-4" key={asset.unit}><div className="text-sm text-slate-400">{asset.label}</div><div className="mt-1 font-mono text-lg font-semibold text-slate-100">{displayQuantity(asset.quantity, asset.unit)}</div><div className="mt-1 truncate text-xs text-slate-500">{asset.unit}</div></div>)}</div>}<div className="mt-3 text-xs text-slate-500">{assetStatus}</div></CardContent></Card>
    <Card className="glass-panel"><CardHeader><CardTitle>Wallet info</CardTitle><CardDescription>Signer threshold and script summaries for this wallet.</CardDescription></CardHeader><CardContent className="grid gap-4 md:grid-cols-3"><div className="rounded-lg border border-border bg-slate-950/60 p-4"><div className="text-sm text-slate-400">Payment script</div><div className="mt-1 font-semibold text-slate-100">{summarizeScript(wallet.paymentScript)}</div></div><div className="rounded-lg border border-border bg-slate-950/60 p-4"><div className="text-sm text-slate-400">Stake script</div><div className="mt-1 font-semibold text-slate-100">{summarizeScript(wallet.stakeScript)}</div></div><div className="rounded-lg border border-border bg-slate-950/60 p-4"><div className="text-sm text-slate-400">Signer hashes</div><div className="mt-1 font-semibold text-slate-100">{wallet.signers.length}</div></div></CardContent></Card>
    <Card className="glass-panel"><CardHeader><CardTitle>Transactions</CardTitle><CardDescription>Recovered from this browser. Pending rooms keep their signatures and invite data after reload.</CardDescription></CardHeader><CardContent>{walletTxs.length === 0 ? <div className="rounded-lg border border-dashed border-border bg-slate-950/40 p-8 text-center text-slate-400">No transactions yet. Create one to start collecting signatures.</div> : <div className="overflow-x-auto"><table className="w-full min-w-[860px] text-left text-sm"><thead className="border-b border-border text-xs uppercase tracking-wide text-slate-500"><tr><th className="py-3 pr-4">Transaction</th><th className="py-3 pr-4">Assets</th><th className="py-3 pr-4">Signatures</th><th className="py-3 pr-4">Status</th><th className="py-3 pr-4">Created</th><th className="py-3 text-right">Actions</th></tr></thead><tbody className="divide-y divide-border">{walletTxs.map((tx) => { const status = txStatus(tx); const signed = signedCount(tx); const pendingSigners = Math.max((tx.requiredSignatures || 0) - signed, 0); return <tr key={tx.id} className="align-top"><td className="py-4 pr-4"><div className="font-semibold text-slate-100">{tx.title}</div><div className="mt-1 max-w-xs truncate text-xs text-slate-500">{tx.recipient || "No recipient"}</div></td><td className="py-4 pr-4 text-slate-300">{(tx.assets?.length ? tx.assets : [{ label: "ADA", quantity: tx.lovelace || "0", unit: "lovelace", id: "ada" }]).map((asset) => <div key={asset.id} className="mb-1"><span className="font-medium">{asset.quantity}</span> <span className="text-slate-400">{asset.label || asset.unit}</span></div>)}</td><td className="py-4 pr-4"><div className="font-semibold text-slate-100">{signed}/{tx.requiredSignatures} signed</div><div className="text-xs text-amber-300">{pendingSigners} pending</div></td><td className="py-4 pr-4"><Badge variant={statusBadge(status)}>{statusIcon(status)} {status}</Badge></td><td className="py-4 pr-4 text-xs text-slate-400">{tx.createdAt ? new Date(tx.createdAt).toLocaleString() : "—"}</td><td className="py-4 text-right"><div className="flex justify-end gap-2"><Button size="sm" variant="secondary" onClick={() => updateStatus(tx.id, "succeeded")}>Succeeded</Button><Button size="sm" variant="destructive" onClick={() => updateStatus(tx.id, "failed")}>Failed</Button></div></td></tr>; })}</tbody></table></div>}</CardContent></Card>
  </main>;
}
